### ISSUE TITLE
Document pyramid_openapi3_validation_error_view permissions

### ISSUE THREAD

**Issue by zupo** [Pylons/pyramid_openapi3#15]
Document that `pyramid_openapi3_validation_error_view()` is [registered without permissions](https://github.com/Pylons/pyramid_openapi3/pull/6#discussion_r272651906).

**Comment by gweis** [comment]
How about getting rid 'pyramid_openapi3_validation_error_view()' and define two custom Exceptions. e.g.: `RequestValidationError` and `ResponseValidationError`.  Both cloud inherit from a common base.
These two exceptions would be raised in the [view wrapper](https://github.com/Pylons/pyramid_openapi3/blob/master/pyramid_openapi3/__init__.py#L70) instead of calling `request.openapi_validated.raise_for_errors()`.

With this in place one can just add pyramid [Custom Exception Views](https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/views.html#custom-exception-views) to handle these exceptions. Provide different handlers for request, response or register an exception view for the base class to handle both. Permission handling would then be under full control by the extension user.

I can probably put a pull request together if this is desired.

**Comment by zupo** [comment]
pyramid_oas3 does something like this: https://github.com/kazuki/pyramid-oas3/blob/master/pyramid_oas3/tween.py#L119

Generally speaking, I'd prefer the approach you described, but then we lose the descriptive errors that openapi-core spits out, such as [`Value is shorter (2) than the minimum length of 3`](https://github.com/Pylons/pyramid_openapi3/blob/master/examples/singlefile/app.py#L148). 

Maybe a good approach is to wrap `request.openapi_validated.raise_for_errors()` in a try-except block and wrap/re-raise its errors with `RequestValidationError` to keep the validation information?

**Comment by gweis** [comment]
It already skips descriptive things, because `request.openapi_validated.raise_for_errors()` throws only the first exception.

I was rather thinking passing the `ValidationResult` class or just the `ValidationResult.errors` as property along with the `custom exceptions`. A custom exception view can then decide how to display one or all errors inside it.

This package could provide a default validation error renderer or the `custom exceptions` could have some sort of default str repr to return a descriptive message in any case

**Comment by zupo** [comment]
You make very valid points. I'd love to see a PR on how you think this would be best approached!

**Comment by gweis** [comment]
Created a pull request #26 .

I think it is fairly complete and requires 0 to very minimal changes for users of this library.

There are a couple of things that could be improved, esp. around re-raising exceptions and preserving orig. stack traces if required. Another thing that could be nice would be to make request / response validation optional, but that would be something for another pull request.

It may not match exactly the coding style in the repo (but I didn't want to repeat myself too much in code), and all test and code checks are passing at least.

**Comment by zupo** [comment]
I think this is no longer needed. Pls tell me otherwise if you think so.
